defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
# development:
#   uri: 'mongodb://skolstad:D2t2Ba$3@staff.mongohq.com:27029/agentrock'
# staging:
#   uri: 'mongodb://skolstad:D2t2Ba$3@staff.mongohq.com:27029/agentrock'
# production:
#   uri: 'mongodb://skolstad:D2t2Ba$3@staff.mongohq.com:27029/agentrock'
development:
  <<: *defaults
  host: localhost
  database: agentrock_development
  mongo:
    database: agentrock_development

test:
  <<: *defaults
  host: localhost
  database: agentrock_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: localhost
  port: 27017
  username: rails
  password: D2t2Ba$3
  database: agentrock
  mongo:
    database: agentrock