defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: agentrock_development
  mongo:
    database: agentrock_development  

test:
  <<: *defaults
  database: agentrock_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: localhost
  port: 27017
  username: rails
  password: D@t@Ba$3
  database: agentrock
  mongo:
    database: agentrock