require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FacebooksController do

  def mock_facebook(stubs={})
    @mock_facebook ||= mock_model(Facebook, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all facebooks as @facebooks" do
      Facebook.stub(:all) { [mock_facebook] }
      get :index
      assigns(:facebooks).should eq([mock_facebook])
    end
  end

  describe "GET show" do
    it "assigns the requested facebook as @facebook" do
      Facebook.stub(:find).with("37") { mock_facebook }
      get :show, :id => "37"
      assigns(:facebook).should be(mock_facebook)
    end
  end

  describe "GET new" do
    it "assigns a new facebook as @facebook" do
      Facebook.stub(:new) { mock_facebook }
      get :new
      assigns(:facebook).should be(mock_facebook)
    end
  end

  describe "GET edit" do
    it "assigns the requested facebook as @facebook" do
      Facebook.stub(:find).with("37") { mock_facebook }
      get :edit, :id => "37"
      assigns(:facebook).should be(mock_facebook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created facebook as @facebook" do
        Facebook.stub(:new).with({'these' => 'params'}) { mock_facebook(:save => true) }
        post :create, :facebook => {'these' => 'params'}
        assigns(:facebook).should be(mock_facebook)
      end

      it "redirects to the created facebook" do
        Facebook.stub(:new) { mock_facebook(:save => true) }
        post :create, :facebook => {}
        response.should redirect_to(facebook_url(mock_facebook))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved facebook as @facebook" do
        Facebook.stub(:new).with({'these' => 'params'}) { mock_facebook(:save => false) }
        post :create, :facebook => {'these' => 'params'}
        assigns(:facebook).should be(mock_facebook)
      end

      it "re-renders the 'new' template" do
        Facebook.stub(:new) { mock_facebook(:save => false) }
        post :create, :facebook => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested facebook" do
        Facebook.stub(:find).with("37") { mock_facebook }
        mock_facebook.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :facebook => {'these' => 'params'}
      end

      it "assigns the requested facebook as @facebook" do
        Facebook.stub(:find) { mock_facebook(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:facebook).should be(mock_facebook)
      end

      it "redirects to the facebook" do
        Facebook.stub(:find) { mock_facebook(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(facebook_url(mock_facebook))
      end
    end

    describe "with invalid params" do
      it "assigns the facebook as @facebook" do
        Facebook.stub(:find) { mock_facebook(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:facebook).should be(mock_facebook)
      end

      it "re-renders the 'edit' template" do
        Facebook.stub(:find) { mock_facebook(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested facebook" do
      Facebook.stub(:find).with("37") { mock_facebook }
      mock_facebook.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the facebooks list" do
      Facebook.stub(:find) { mock_facebook }
      delete :destroy, :id => "1"
      response.should redirect_to(facebooks_url)
    end
  end

end
